repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args: [--max-line-length=88]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
        name: mypy-backend
        files: ^backend/
        args: [--ignore-missing-imports, --explicit-package-bases]
        additional_dependencies:
          - types-requests
          - fastapi
          - httpx
          - uvicorn
          - pydantic
          - python-dotenv
      - id: mypy
        name: mypy-frontend
        files: ^frontend/
        args: [--ignore-missing-imports, --explicit-package-bases]
        additional_dependencies:
          - types-requests
          - pydantic
          - streamlit
          - python-dotenv

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.4
    hooks:
      - id: bandit
